import QueryProvider from '@/providers/query-providers'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const zenSerif = localFont({
  src: '../font/ZEN-SERIF-TTF-Regular.woff2',
  variable: '--font-zen-serif',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={`${zenSerif.variable} font-pretendard`}>{children}</body>
      </QueryProvider>
    </html>
  )
}
